if true then
  return {}
end

-- local telescope = require("telescope")
--
-- return {
--   "telescope.nvim",
--   dependencies = {
--     "nvim-telescope/telescope-live-grep-args.nvim",
--   },
--   opts = function(_, opts)
--     -- require("telescope").load_extension("live_grep_args")
--     local lga_actions = require("telescope-live-grep-args.actions")
--     opts.extensions = {
--       live_grep_args = {
--         auto_quoting = false, -- enable/disable auto-quoting
--         -- define mappings, e.g.
--         mappings = { -- extend mappings
--           n = {
--             ["<leader>p"] = lga_actions.quote_prompt(),
--             ["<leader>i"] = lga_actions.quote_prompt({ postfix = " --iglob " }),
--             ["<leader>t"] = lga_actions.quote_prompt({ postfix = " -t" }),
--             ["<leader>b"] = lga_actions.quote_prompt({ postfix = " -tcpp --iglob *" }),
--           },
--         },
--         -- ... also accepts theme settings, for example:
--         -- theme = "dropdown", -- use dropdown theme
--         -- theme = { }, -- use own theme spec
--         -- layout_config = { mirror=true }, -- mirror preview pane
--       },
--     }
--     opts.defaults = vim.tbl_extend("force", opts.defaults, {
--       layout_config = {
--         horizontal = { width = 0.9 },
--       },
--     })
--   end,
--   keys = {
--     {
--       "<leader>/",
--       function()
--         telescope.extensions.live_grep_args.live_grep_args()
--       end,
--     },
--   },
-- }
